name: Bug Report
description: File a bug report
labels: "Bug"
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report! Before
        submitting your issue, make sure this has not been already
        reported or if it works with the latest published version
        of Docker snap.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: >
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To reproduce
      description: >
        Provide a step-by-step instruction of how to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment information for bug reproduction
      description: >
        Kindly copy **all** the commands below, run them in your terminal,
        and share the results here.
          ```bash
            echo -e "\nDocker snap information:"
            snap list docker

            echo -e "\nPlug Connections:"
            snap connections docker

            echo -e "\nSnapd information:"
            snap version

            echo -e "\nOS release:"
            cat /etc/os-release

            echo -e "\nKernel version and architecture:"
            uname -orvm
          ```
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional information
      description: >
        Provide any additional information, including relevant logs.
    validations:
      required: true
