name: Bug Report
description: File a bug report
labels: "Bug"
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report! Before
        submitting your issue, make sure this has not been already
        reported or if it works with the latest published version
        of Docker snap.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: >
        If applicable, add screenshots to help explain your
        problem. Provide any additional information you may find useful here.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: >
        Provide a step-by-step instruction of how to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information for Bug Reproduction
      description: >
        Kindly copy the commands below, run them in your terminal,
        and share the results here.
          ```bash
            snap list docker; echo;
            snap connections docker; echo;
            snap version; echo;
            cat /etc/os-release; echo;
            uname -orvm;
          ```
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output.
    validations:
      required: true
