job_queue: ${{ matrix.queue }}
global_timeout: 3600
output_timeout: 1800
provision_data:
    distro: "noble"
test_data:

  # Copy files from the GH runner to the Testflinger Agent
  attachments:
    - local: ".github/workflows/scripts"
      agent: "scripts"

  # Run commands on the Testflinger Agent
  test_cmds: |
    #!/usr/bin/env bash
    set -ex

    # List the attached files
    find attachments/test

    SCRIPTS=./attachments/test/scripts

    echo "Testing: DEVICE_IP = $DEVICE_IP"
    # Setup the environment on the target device
    ssh ubuntu@$DEVICE_IP "$(< $SCRIPTS/setup.sh)"

    # Reboot it
    ssh ubuntu@$DEVICE_IP "sudo reboot &"

    echo "Wait for the device to boot and start its SSH server"
    $SCRIPTS/wait_for_port.sh $DEVICE_IP 22

    # Run the tests
    ssh ubuntu@$DEVICE_IP "$(< $SCRIPTS/test.sh)"