#!/bin/bash -u
# Fork of wrapper at https://github.com/canonical/gpu-snap #
# The provider-wrapper is required on core systems, not classic system #

. "${SNAP}/usr/share/nvidia-container-toolkit/lib"

# Classic does not require this wrapper #
if [ "${NVIDIA_SUPPORT_CLASSIC}" == "true" ] ; then
    exec "$@"
fi

if [ "${NVIDIA_SUPPORT_CORE}" == "true" ] ; then
    if snapctl is-connected gpu-2404; then
        exec "${SNAP}/gpu-2404/bin/gpu-2404-provider-wrapper" "$@"
    fi

    # Core 22 does not require this wrapper #
    if snapctl is-connected graphics-core22  ; then
        exec "$@"
    fi

    exit_inf "GPU user-space content provider not connected."
fi
