#!/bin/bash

# This script implements the connect hook for snap's graphics plugs

set -eux

HOOK_LOG="${SNAP_COMMON}/hooks/${SNAP_REVISION}/$(basename "$0").log" && mkdir -p "${HOOK_LOG%/*}"
exec &> >(tee -a "${HOOK_LOG}")

. "${SNAP}/usr/share/nvidia-container-toolkit/lib"

# Just exit if NVIDIA support is disabled #
[ "${NVIDIA_SUPPORT_DISABLED}" != "true" ] || exit 0

# Ensure hardware present #
nvidia_hw_ensure

# Restart services to reflect any changes if required #
# If oneshot services are inactive they don't respond to restart, so stop/start #
snapctl stop "${SNAP_NAME}.nvidia-container-toolkit"
snapctl start --enable "${SNAP_NAME}.nvidia-container-toolkit"
snapctl restart "${SNAP_NAME}.dockerd"
