#!/bin/bash -u
# Detect if nvidia support enabled, and available, for a system type #

. "${SNAP}/usr/share/nvidia-container-toolkit/lib"

NVIDIA_SUPPORT_DISABLED="$(snapctl get nvidia-support.disabled)"

export NVIDIA_SUPPORT_CORE="false"
export NVIDIA_SUPPORT_CLASSIC="false"

if [ -L "/var/lib/snapd/hostfs/usr/lib/${ARCH_TRIPLET}/libcuda.so" ]; then
    export NVIDIA_SUPPORT_CLASSIC="true"
    echo "Running on Classic system"
else if snapctl is-connected gpu-2404 || snapctl is-connected graphics-core22; then
    export NVIDIA_SUPPORT_CORE="true"
    echo "Running on Ubuntu Core system"
else
    exit_inf "No NVIDIA support detected. For NVIDIA support, please refer to https://github.com/canonical/docker-snap"
fi

# Just exit if NVIDIA support is disabled #
[ "${NVIDIA_SUPPORT_DISABLED}" != "true" ] || exit_inf "NVIDIA support disabled by user"

exec "$@"
