name: Build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: snapcore/action-build@v1
        id: snapcraft
        with:
          snapcraft-args: snap --output docker_${{ github.run_id}}.snap

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: docker_${{ github.run_id}}.snap
          path: ${{ steps.snapcraft.outputs.snap }}

