name: Nvidia Graphics Tests

on:
    workflow_run:
      workflows:
        - "Smoke Test"
      types:
        - completed

jobs:

    # build-and-upload-artifact:
    #     runs-on: [ubuntu-latest]
    #     env:
    #         PR_NUMBER: ${{ github.event.number }}
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v4
            
    #         - name: Setup upterm session
    #           uses: lhotari/action-upterm@v1
    #           with:
    #             wait-timeout-minutes: 2

    #         - name: Build docker snap
    #           uses: snapcore/action-build@v1
    #           id: snapcraft
    #           with:
    #             snapcraft-args: snap --output docker.snap
            
    #         - name: Install snapcraft
    #           run: |
    #             sudo snap install snapcraft --classic
            
    #         - name: Upload artifact to snapstore branch
    #           run: |
    #             export SNAPCRAFT_STORE_CREDENTIALS="${{ secrets.SNAPCRAFT_LOGIN }}"
    #             snapcraft upload ${{steps.snapcraft.outputs.snap}} --release latest/edge/pr-${{ env.PR_NUMBER }}

    test:
        # needs: build-and-upload-artifact
        runs-on: [self-hosted, testflinger]
        strategy:
          fail-fast: true
          matrix:
            queue:
              # - 202007-28059
              # - 202008-2816s7
              - 202112-29789
            data_source:
              - "distro: noble"
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # - name: Setup upterm session
            #   uses: lhotari/action-upterm@v1
            #   with:
            #     wait-timeout-minutes: 2

            - name: Submit Testflinger job
              uses: canonical/testflinger/.github/actions/submit@main
              with:
                poll: true
                job-path: .github/workflows/testflinger/nvidia.yaml

