name: Nvidia Graphics Tests

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      fail_fast:
        description: 'Stop after first distro failure'
        default: false
        type: boolean
      run_id:
        description: 'Run ID'
        required: true
        type: string

jobs:
    test:
        runs-on: [self-hosted, testflinger]
        strategy:
          fail-fast: ${{ inputs.fail_fast }}
          matrix:
            distro: 
              - noble
              - core22-latest
              - core24-latest
        env:
          TESTFLINGER_DIR: .github/workflows/testflinger
          SNAP_CHANNEL: latest/edge/runid-${{ inputs.run_id }}
        steps:
            - name: Event data
              run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Testflinger job
              env:
                JOB_QUEUE: docker-nvidia
                DISTRO: ${{ matrix.distro }}
              run: |

                # Prepare job
                envsubst '$JOB_QUEUE $DISTRO' \
                  < $TESTFLINGER_DIR/nvidia-job.yaml \
                  > $TESTFLINGER_DIR/nvidia-job.temp
                mv $TESTFLINGER_DIR/nvidia-job.temp $TESTFLINGER_DIR/nvidia-job.yaml
                
                # Prepare setup script
                envsubst '$SNAP_CHANNEL' \
                  < $TESTFLINGER_DIR/scripts/setup.sh \
                  > $TESTFLINGER_DIR/scripts/setup.temp
                mv $TESTFLINGER_DIR/scripts/setup.temp $TESTFLINGER_DIR/scripts/setup.sh

            - name: Run tests
              uses: canonical/testflinger/.github/actions/submit@main
              with:
                poll: true
                job-path: ${{ env.TESTFLINGER_DIR }}/nvidia-job.yaml
