name: Nvidia Graphics Tests

on:
  # Uncomment this trigger only during workflow development
  # pull_request:
  #   branches: [ main ]
  # Manual trigger
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run id number'
        required: true
        type: number

jobs:
    test:
        runs-on: [self-hosted, testflinger]
        env:
          TESTFLINGER_DIR: .github/workflows/testflinger
        strategy:
          fail-fast: true
          matrix:
            job-queue:
              - 202007-28059
              # - 202008-2816s7
              # - 202112-29789
              # noprovision node, for CI testing
              # - 202302-31212
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get the artifact
              uses: dawidd6/action-download-artifact@v6
              with:
                workflow: build.yml
                name: docker_${{ inputs.run_id }}.snap

            - name: Publish to Store
              uses: snapcore/action-publish@v1
              env:
                SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
              with:
                snap: docker_${{ inputs.run_id }}.snap
                release: latest/edge/runid-${{ inputs.run_id }}

            - name: Create Testflinger job queue
              run: |
                export JOB_QUEUE="${{ matrix.job-queue }}"
                export SNAP_CHANNEL="latest/edge/runid-${{ inputs.run_id }}"

                envsubst '$JOB_QUEUE' \
                  < $TESTFLINGER_DIR/nvidia-job.yaml \
                  > $TESTFLINGER_DIR/nvidia-job.temp

                envsubst '$SNAP_CHANNEL' \
                  < $TESTFLINGER_DIR/scripts/setup.sh \
                  > $TESTFLINGER_DIR/scripts/setup.temp

                mv $TESTFLINGER_DIR/nvidia-job.temp $TESTFLINGER_DIR/nvidia-job.yaml
                mv $TESTFLINGER_DIR/scripts/setup.temp $TESTFLINGER_DIR/scripts/setup.sh

            - name: Submit Testflinger job
              uses: canonical/testflinger/.github/actions/submit@main
              with:
                poll: true
                job-path: ${{ env.TESTFLINGER_DIR }}/nvidia-job.yaml
