name: Nvidia Graphics Tests

on:
  # Uncomment this trigger only during workflow development
  # pull_request:
  #   branches: [ main ]
  # Manual trigger
  workflow_dispatch:
    inputs:
      pr_num:
        description: 'Pull Request number'
        required: true
        type: number

jobs:

    test:
        needs: publish
        if: ${{ always() && !failure() && !cancelled() }}
        runs-on: [self-hosted, testflinger]
        env:
          TESTFLINGER_DIR: .github/workflows/testflinger
          JOB_QUEUE: docker-nvidia
          SNAP_CHANNEL: latest/edge/pr-${{ inputs.pr_num }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Testflinger job queue
              run: |

                targetDistros=("noble" "core22-latest")

                for DISTRO in ${targetDistros[@]}; do
                  export DISTRO

                  envsubst '$JOB_QUEUE $DISTRO' \
                    < $TESTFLINGER_DIR/nvidia-job.yaml \
                    > $TESTFLINGER_DIR/nvidia-job-"$DISTRO".temp

                  mv $TESTFLINGER_DIR/nvidia-job-"$DISTRO".temp $TESTFLINGER_DIR/nvidia-job-"$DISTRO".yaml
                done

                envsubst '$SNAP_CHANNEL' \
                  < $TESTFLINGER_DIR/scripts/setup.sh \
                  > $TESTFLINGER_DIR/scripts/setup.temp

                mv $TESTFLINGER_DIR/scripts/setup.temp $TESTFLINGER_DIR/scripts/setup.sh

            - name: Submit Testflinger job for Ubuntu 24.04 (Noble)
              uses: canonical/testflinger/.github/actions/submit@main
              with:
                poll: true
                job-path: ${{ env.TESTFLINGER_DIR }}/nvidia-job-noble.yaml

            - name: Submit Testflinger job for Ubuntu Core 22
              uses: canonical/testflinger/.github/actions/submit@main
              with:
                poll: true
                job-path: ${{ env.TESTFLINGER_DIR }}/nvidia-job-core22-latest.yaml
