name: Nvidia Graphics Tests

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run id number'
        required: true
        type: number
      publish:
        description: 'Publish to Store'
        default: true
        type: boolean
      fail_fast:
        description: 'Stop after first distro failure'
        default: false
        type: boolean

jobs:
    publish:
        if: ${{ inputs.publish == true }}
        runs-on: ubuntu-latest
        steps:
            # Download snap artifact from a previous smoke-test/build GitHub Workflow run
            - name: Download snap artifact
              uses: dawidd6/action-download-artifact@v9
              with:
                run_id: ${{ inputs.run_id }}
                name: docker_${{ inputs.run_id }}_amd64.snap
            
            # Publish snap to Store so it can be installed on the test devices
            - name: Publish snap to Store
              uses: snapcore/action-publish@v1
              env:
                SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
              with:
                snap: docker_${{ inputs.run_id }}_amd64.snap
                release: latest/edge/runid-${{ inputs.run_id }}

    test:
        needs: publish
        # Run also when previous job has been skipped (publish not required)
        if: ${{ always() && !failure() && !cancelled() }}
        runs-on: [self-hosted, testflinger]
        strategy:
          fail-fast: ${{ inputs.fail_fast }}
          matrix:
            distro: 
              - noble
              - core22-latest
              - core24-latest
        env:
          TESTFLINGER_DIR: .github/workflows/testflinger
          SNAP_CHANNEL: latest/edge/runid-${{ inputs.run_id }}
        steps:
            - name: Event data
              run: "echo ::notice::Snap channel: $SNAP_CHANNEL"

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Testflinger job
              env:
                JOB_QUEUE: docker-nvidia
                DISTRO: ${{ matrix.distro }}
              run: |

                # Prepare job
                envsubst '$JOB_QUEUE $DISTRO' \
                  < $TESTFLINGER_DIR/nvidia-job.yaml \
                  > $TESTFLINGER_DIR/nvidia-job.temp
                mv $TESTFLINGER_DIR/nvidia-job.temp $TESTFLINGER_DIR/nvidia-job.yaml
                
                # Prepare setup script
                envsubst '$SNAP_CHANNEL' \
                  < $TESTFLINGER_DIR/scripts/setup.sh \
                  > $TESTFLINGER_DIR/scripts/setup.temp
                mv $TESTFLINGER_DIR/scripts/setup.temp $TESTFLINGER_DIR/scripts/setup.sh

                # Prepare refresh-test script
                envsubst '$SNAP_CHANNEL' \
                  < $TESTFLINGER_DIR/scripts/refresh-test.sh \
                  > $TESTFLINGER_DIR/scripts/refresh-test.temp
                mv $TESTFLINGER_DIR/scripts/refresh-test.temp $TESTFLINGER_DIR/scripts/refresh-test.sh

            - name: Run tests
              uses: canonical/testflinger/.github/actions/submit@main
              with:
                poll: true
                job-path: ${{ env.TESTFLINGER_DIR }}/nvidia-job.yaml
