name: Publish

on:
  workflow_run:
    workflows: [ "Smoke Test" ]  # Trigger after "Smoke Test" workflow
    types:
      - completed  # Run after workflow completes

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Get triggering PR number
              id: get-pr
              run: |
                PR_NUMBER=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} \
                  --jq '.pull_requests[0].number')
                if [[ -z "$PR_NUMBER" ]]; then
                  echo "PR_NUMBER=none" >> "$GITHUB_ENV"
                else
                  echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"
                fi
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Get the artifact
              uses: dawidd6/action-download-artifact@v8
              with:
                run_id: ${{ github.event.workflow_run.id }}
                name: docker_${{ inputs.run_id }}_amd64.snap

            - name: Publish to Store
              uses: snapcore/action-publish@v1
              env:
                SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
              with:
                snap: docker_${{ inputs.run_id }}_amd64.snap
                release: latest/edge/pr--${{ inputs.run_id }}
