#!/bin/bash

set -eu

# Just exit if NVIDIA support is disabled #
NVIDIA_SUPPORT_DISABLED="$(snapctl get nvidia-support.disabled)"
[ "${NVIDIA_SUPPORT_DISABLED}" != "true" ] || exit 0

# Ensure nvidia support setup correctly #
if snapctl is-connected graphics-core22 ; then

    # Only set this up if the system has an nvidia card available #
    grep -Eq "^nvidia" /proc/modules || exit 0
    test -c /dev/nvidiactl || exit 0
    echo "NVIDIA detected"

    # Restart services to reflect any changes if required #
    # Have to called by name - nvidia-container-toolkik is inactive and won't be included with just snap name #
    snapctl restart "${SNAP_NAME}.nvidia-container-toolkit"
    snapctl restart "${SNAP_NAME}.dockerd"

fi
