#!/bin/bash -e

# Ensure nvidia support setup correctly #
if snapctl is-connected nvidia-core22:graphics-core22 ; then

    # Generate the CDI config #
    $SNAP/usr/bin/nvidia-ctk cdi generate --nvidia-ctk-path "$SNAP/usr/bin/nvidia-ctk" --output="$SNAP_DATA/etc/cdi/nvidia.yaml"

    # Generate the dockerd runtime config #
    $SNAP/usr/bin/nvidia-ctk runtime configure --runtime=docker --runtime-path "$SNAP/usr/bin/nvidia-ctk" --config "$SNAP_DATA/config/daemon.json"

    # Restart dockerd to reflect any changes #
    snap restart "$SNAP_NAME.dockerd"

fi
