#!/bin/bash -e

# copy the config file from $SNAP into $SNAP_COMMON if it doesn't exist
if [ ! -f "$SNAP_COMMON/config/daemon.json" ]; then
    mkdir -p "$SNAP_COMMON/config"
    cp "$SNAP/config/daemon.json" "$SNAP_COMMON/config/daemon.json"
fi
