#!/bin/bash

set -eu

. "${SNAP}/usr/share/nvidia-container-toolkit/lib"

# ensure the layouts dir for /etc/{stuff} exists
mkdir -p "$SNAP_DATA/etc/docker"
mkdir -p "$SNAP_DATA/config"
ensure_nvidia_data_dirs

# copy the config file from $SNAP into $SNAP_DATA if it doesn't exist
if [ ! -f "$SNAP_DATA/config/daemon.json" ]; then
    cp "$SNAP/config/daemon.json" "$SNAP_DATA/config/daemon.json"
fi
